apiVersion: v1
kind: Pod
metadata:
 name: master-nginx
 labels:
   app: master-nginx
spec:
 containers:
 - name: master-nginx
   image: aftab005/cloudethix-master-nginx-aftab:v3
   ports:
   - containerPort: 80
